### ISSUE TITLE
Reward curve uses floats

### ISSUE THREAD

**Issue by everhusk** [ava-labs/avalanche-go#309]
**Describe the bug**
The reward curve uses floats, this will cause inconsistencies across machines. Didn't see it tracked anywhere so I thought i'd make an issue for it.

https://github.com/ava-labs/gecko/blob/master/vms/platformvm/reward.go#L13

**Additional context**
Just wanted to make a note on one possible solution to the problem. Take a look at how substrate accomplishes this: https://github.com/paritytech/substrate/blob/master/frame/staking/src/inflation.rs#L32.

Hope it helps!

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by StephenButtolph** [comment]
Thanks for putting this into an issue. This is fixed by #381 where the real minting function is defined.
